[package]

name = "news"
version = "2016.7.13"
authors = ["Andrew Kubera <andrewkubera@gmail.com>"]

build = "build.rs"

[lib]
name = "news"
# crate-type = ["dylib"]

[dependencies]
pencil = "^0.2"
yaml-rust = "^0.3"
webbrowser = "*"
# walkdir = {path = "src/walkdir"}
horrorshow = "0.6"


# iron = "0.2.2"
# router = "*"

# rust-haml = "*"

# maud = "*"
# maud_macros = "*"

# staticfile = "*"
# logger = "*"
# pencil = "^0.1"

[build-dependencies]
yaml-rust = "0.3"
yassyl = { path = "yassyl" }
