[package]

name = "news"
version = "2015.9.23"
authors = ["Andrew Kubera <andrewkubera@gmail.com>"]

[dependencies]
iron = "0.2.2"
router = "*"
yaml-rust = "0.2.1"
# rust-haml = "*"

# maud = "*"
# maud_macros = "*"

horrorshow = "0.5.3"
staticfile = "*"
logger = "*"

[dependencies.mount]
git = "https://github.com/iron/mount.git"
