[package]

name = "news"
version = "2016.3.10"
authors = ["Andrew Kubera <andrewkubera@gmail.com>"]

[dependencies]
# iron = "0.2.2"
# router = "*"
yaml-rust = "*"

# rust-haml = "*"

# maud = "*"
# maud_macros = "*"

horrorshow = "0.5.5"
# staticfile = "*"
# logger = "*"
pencil = "*"
webbrowser = "*"

# [dependencies.mount]
# git = "https://github.com/iron/mount.git"


[lib]
name = "news"
plugin = true
crate-type = ["dylib"]
