[package]

name = "news"
version = "2016.7.13"
authors = ["Andrew Kubera <andrewkubera@gmail.com>"]

[dependencies]
yaml-rust = "^0.3"
maud = "0.17"
maud_macros = "0.17"

pulldown-cmark = "*"
maud-pulldown-cmark = "0.5"

time = "*"

rouille = "1.0.3"
