[package]
name = "news"
version = "2018.8.9"
authors = ["Andrew Kubera <andrewkubera@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust = "^0.3"

maud = "0.19"
maud_macros = "0.19"

pulldown-cmark = "*"
maud-pulldown-cmark = "0.5"

time = "*"

rouille = "1.0.3"
walkdir = "1"
regex = "0.1.80"
