
### Project Style Guide ###

tab_spaces = 2
wrap_comments = false
normalise_comments = true
fn_brace_style = 'AlwaysNextLine'
max_width = 120
impl_empty_single_line = false
fn_empty_single_line = false
match_block_trailing_comma = true


### Strictly-Enforced Default Values ###

skip_children = false
ideal_width = 80
fn_call_width = 60
struct_lit_width = 16
newline_style = 'Unix'
item_brace_style = 'SameLineWhere'
fn_single_line = false
fn_return_indent = 'WithArgs'
fn_args_paren_newline = true
fn_args_density = 'Tall'
fn_args_layout = 'Visual'
fn_arg_indent = 'Visual'
type_punctuation_density = 'Wide'
where_density = 'CompressedIfEmpty'
where_indent = 'Tabbed'
where_layout = 'Vertical'
where_pred_indent = 'Visual'
where_trailing_comma = false
generics_indent = 'Visual'
struct_trailing_comma = 'Vertical'
struct_lit_trailing_comma = 'Vertical'
struct_lit_style = 'Block'
struct_lit_multiline_style = 'PreferSingle'
enum_trailing_comma = true
chain_base_indent = 'Visual'
chain_indent = 'Visual'
reorder_imports = false
single_line_if_else = false
format_strings = true
force_format_strings = false
chains_overflow_last = true
take_source_hints = true
hard_tabs = false
wrap_match_arms = true
match_wildcard_trailing_comma = true
